# Site settings
title: Another Blog
url: "https://xbshnn.github.io/"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "/Modern-Computer-Graphics" # the prefix of your site uri, eg. `"/jekyll-theme-EasyBook"` or empty string `""`
#timezone: Asia/Chongqing
description: >
  分享自己的学习心得！

# Your information
email: 1700012115@pku.edu.cn
author: linb han
# avatar: "//www.gravatar.com/avatar/your_email_md5?d=mm&s=135"
profile: 好好学习，认真做笔记
#twitter_username: twitter_username
#github_username:  xbshnn
profile_links:
  Email: "mailto:1700012115@pku.edu.cn"
  GitHub: "https://github.com/xbshnn/"
  # You can add more profile links above, or edit _includes/sidebar.html 

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

excerpt_separator: <!--more-->

header:
  links:             # Links on the header. Link to in-site page with a slash as prefix
    About: /about/
    Category: /category/
    Donate: /

permalink: /archivers/:title
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

# https://jekyllrb.com/docs/configuration/#precedence
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
